{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "data-prepper.fullname" . }}
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.serviceMonitor.extraLabels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "data-prepper.selectorLabels" . | nindent 4 }}
  endpoints:
  {{- toYaml .Values.serviceMonitor.metricsEndpoints | nindent 2 }}
{{- end }}

