apiVersion: v1
data:
  # TODO: work out how to pass through the yaml
  data-prepper-config.yaml: 'ssl: false'
kind: ConfigMap
metadata:
  name: {{ include "data-prepper.configName" . }}
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}

